; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

; Generated by VC++ for Common Language Runtime
.file "D:\UserData\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cpp"
