# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-19 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='path',
            field=models.CharField(default='hehe', max_length=512),
            preserve_default=False,
        ),
    ]
